# Generated by Django 5.2.8 on 2025-11-19 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок поста')),
                ('content', models.TextField(verbose_name='Контент поста')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('edited', models.BooleanField(default=False, verbose_name='Изменен ли данный пост?')),
            ],
        ),
    ]
