# Generated by Django 5.2.8 on 2025-11-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_options_postattachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachments',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назание файла'),
        ),
    ]
