# Generated by Django 5.2.8 on 2025-11-24 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postattachments_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Контент комментария')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('edited', models.BooleanField(default=False, verbose_name='Изменен ли данный пост?')),
                ('pinned', models.BooleanField(default=False, verbose_name='Прикреплен ли данный комментарий?')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
