# Generated by Django 5.2.8 on 2025-12-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_content_en_post_content_ru_post_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Контент комментария'),
        ),
        migrations.AddField(
            model_name='comments',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Контент комментария'),
        ),
    ]
